### ISSUE TITLE
After deployed, I got 403 forbidden

### ISSUE THREAD

**Issue by areshero** [Miserlou/django-zappa#100]
The deployment is successful, however when I tried to access the url, I got {"message":"Forbidden"}. Don't know what happened...

**Comment by collingreen** [comment]
Can you post the results from `zappa tail <stage>`?

**Comment by JavierLopezMunoz** [comment]
I had the same message when I undeploy and deploy back a project which I did certify using "zappa certify". The "Custom Domain Name" in the API Gateway did not have "Base Path Mappings".

I solve it by manually set "Base Path Mappings" to my "Custom Domain Name" manually in the AWS API Gateway console.

I hope this helps.

**Comment by Miserlou** [comment]
Thanks for the update, but this project is deprecated and discussion should be moved to Zappa core. Thanks!
