### ISSUE TITLE
aws region-specific bug

### ISSUE THREAD

**Issue by riceluxs1t** [Miserlou/django-zappa#110]
When I set my ZAPPA_SETTINGS to be something like below

ZAPPA_SETTINGS = {
    'dev': {
        'aws_region': 'ap-northeast-1',
        's3_bucket': 'MY_BUCKET_NAME,
        'settings_file': 'PATH_TO_MY_SETTINGS/settings.py'
    }
}

the standrad "python manage.py deploy dev" command doesn't work.

However, If I remove the "aws_region" parameter, things magically work. I believe this behaviour is easily reproduciable and might be non-us-region specific.

**Comment by collingreen** [comment]
Are lambda and api gateway available in ap-northeast-1?

Either way, can you post the relevant part of the stack trace? It might be something somebody can help fix, or worst case it will help others search for it.

**Comment by riceluxs1t** [comment]
@collingreen thank you for your quick response. I tried to reproduce the issue so I can get some stack traces but am not able to at the moment.

The sequence of things I did was 
1) Created a bucket to be used in my ZAPPA_SETTINGS beforehand, set my ZAPPA_SETTINGS accordingly, ran the deploy command, it failed.

2) Changed the ZAPPA_SETTINGS to use a new bucket name (without actually creating it), ran the deploy command, everything worked fine. Then noticed things are up and running in a us region.

3) Supplied the region parameter (ap-northeast-1) into my ZAPPA_SETTINGS, left the bucket name unchanged, ran the command, it failed.

4) Supplied the region parameter, changed the bucket name parameter to a new one (not yet created), ran the command, it failed.

5) Removed the region parameter, left the bucket name unchanged, ran the command, things worked.

^ 
Left me with a conclusion that something region-specific is messing things up. (which I have no clue about). But at the moment, I can't reproduce the behavior.

any guess? please give me some guidance on whether or not to keep this issue open in case I run into that behavior again. I am developing a micro service and need to have it up and running in the ap-north-east region and (hopefully not) might run into this issue again

**Comment by jondanao** [comment]
I concur that this is a bug.

```python
ZAPPA_SETTINGS = {
    'dev': {
        'aws_region': 'ap-southeast-1',
        's3_bucket': 'django.lambda',
        'settings_file': './project/settings.py',
    }
}
```

But my bucket was still created in `US Standard` that is why I get this error because they are not in the same region.

```
botocore.exceptions.ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```
