### ISSUE TITLE
Postgres psycopg2

### ISSUE THREAD

**Issue by fchevitarese** [Miserlou/django-zappa#123]
Hey guys! 

First of all, thanks for this app, it amazing =D

Im trying to use it with postgres RDS but, the Sphere app does not run. I get always request timed out. 
There's any kind of different driver for use postgres with lambda? 
Im using this as default engine -> django.db.backends.postgresql_psycopg2

Is that right ? 

Thanks in advance! =D

**Comment by Miserlou** [comment]
With latest D-Z, postgres should work fine as it's provided by [lambda_packages](https://github.com/Miserlou/lambda-packages).

Is your database in a VPC?

**Comment by fchevitarese** [comment]
No, it's necessary? I was following the instructions on the video posted on youtube, but as my project uses pgsql i tried with it =D

**Comment by Miserlou** [comment]
A time out suggests that you're just unable to reach the database. You need to specifically make the database available to the outside world, or put both your database and your zappa app inside the same VPC.

**Comment by fchevitarese** [comment]
Ok. 
I found a post i will follow it ;) 
https://serverlesscode.com/post/zappa-wsgi-for-python-pt-2/

If i dont get it working i come back :P 

Thanks !!!
