### ISSUE TITLE
Switch to explicit redirect handling

### ISSUE THREAD

**Issue by codingjoe** [Miserlou/django-zappa#13]
The [implicit status code handling](https://github.com/Miserlou/django-zappa/blob/master/django_zappa/middleware.py#L51) for redirects will moste likely misbehave if any other than a 200 response code provides a location.

A good example would be a 201 CREATED, should include a location header.

I guess it makes more sense to filter for 3xx status codes rather than NOT 200.

**Comment by Miserlou** [comment]
Good catch!

**Comment by codingjoe** [comment]
```python
if response.status_code[0] == 3 and response.has_header('Location'):
```

**Comment by Miserlou** [comment]
Send a PR please! (And if you have any DCC-type contributions to make, those would be appreciated as well!)

**Comment by codingjoe** [comment]
haha, ok will do.
