### ISSUE TITLE
bug when using Flask due to django specific code

### ISSUE THREAD

**Issue by sdementen** [Miserlou/django-zappa#137]
The following code in cli.py
```
                # Copy our Django app into root of our package.
                # It doesn't work otherwise.
                base = __file__.rsplit(os.sep, 1)[0]
                django_py = ''.join(os.path.join([base, os.sep, 'ext', os.sep, 'django.py']))
                lambda_zip.write(django_py, 'django_zappa_app.py')
```
is executed irrespective of the type of application and fails for Flask apps.
It should be probably only executed `if self.django_settings:`

**Comment by Miserlou** [comment]
Are you on Windows, perchance?

**Comment by Miserlou** [comment]
Wait, this is the Django-Zappa project, which is now deprecated.

Please either report upstream, or don't use Django-Zappa for flask.
