### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by sdillinger** [Miserlou/django-zappa#151]
This is a great project and I hope to be able to contribute in the future. Thanks for taking the time to create it.

I read the docs and watched a video or two, but I still don't quite understand how the setup works.

I have Django on an EC2 instance in VPC subnet connected to an RDS instance in the same subnet.

Do I simply install the AWS SDK and then follow the simple zappa directions? 

Does the setup process try to create its own VPC? Will it make any changes to my existing VPCs?

If my requirements file is up-to-date do I need to be in a virtual environment? My project is not in one (long story).

Thanks in advance for clarifications.

**Comment by Miserlou** [comment]
Hey Steve, please use the Zappa main project for discussion, django-zappa is deprecated.

Zappa doesn't create its own VPCs, you just specify them in your settings. Currently a virtualenv is a requirement, but there is an open ticket to allow supping a req.txt file instead.

For specific questions, please hop by the slack: https://slack.zappa.io

**Comment by sdillinger** [comment]
Sorry about that Miserlou-  will do.

Thanks for the slack link...
