### ISSUE TITLE
Lower default memory usage, make configurable.

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/django-zappa#23]
512 is probably too high for a default, I bet we can drop that by half at least.

**Comment by mathom** [comment]
I've added the configuration option in https://github.com/Miserlou/django-zappa/pull/30 but I haven't tested much at lower memory settings so I left the default at 512.

**Comment by mathom** [comment]
In my little "Hello World" example I use to test this stuff it's using ~25MB to serve on Lambda:
```
REPORT RequestId: cf31d47f-daa0-11e5-b9dc-494ab6910a45	Duration: 4.32 ms	Billed Duration: 100 ms Memory Size: 256 MB	Max Memory Used: 24 MB
```

It would be interesting to see some larger examples and set the default accordingly.

**Comment by Miserlou** [comment]
Yeah, I'm wondering what happens if you have many Users, many objects in a query, etc.

**Comment by collingreen** [comment]
would be pretty amazing to have another lambda task crawl the logs and adjust accordingly
