### ISSUE TITLE
Analyze Profiler Output

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/django-zappa#24]
This ended up being way more detailed than I anticipated.
[profile.txt](https://github.com/Miserlou/django-zappa/files/141600/profile.txt)

**Comment by Miserlou** [comment]
Well, right off the bat it looks like:

(call)|         1|      2.70472|      2.70472| 71.79%|# /private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-iHBwmU/Django/django/__init__.py:8 setup

70% of the time is spent setting up Django. That seems like a good starting point.

The majority of the rest is in

(call)|         1|      1.04399|      1.04399| 27.71%|# /private/var/folders/00/vp4bg2md3ng4sqkg3hrz_j1003frjd/T/pip-build-iHBwmU/Django/django/core/handlers/wsgi.py:162 __call__

and everything else looks pretty trivial.

**Comment by Miserlou** [comment]
In setup(), populate eats the most..

**Comment by Miserlou** [comment]
Poking @stephrdev in case you have any insights/magic tricks you can think of to throw at this!

**Comment by Miserlou** [comment]
Ticket for upstream discussion: https://code.djangoproject.com/ticket/26284

**Comment by Miserlou** [comment]
We got this down to ~30ms.

**Comment by sridhar562345** [comment]
@Miserlou can you provide more details on how you optimized this?

**Comment by souravjamwal77** [comment]
Hi @sridhar562345 The new, official, and actively managed Zappa project is [here](https://github.com/zappa/Zappa).
You can post your issue.
