### ISSUE TITLE
Admin redirect

### ISSUE THREAD

**Issue by eekolife** [Miserlou/django-zappa#25]
I setup a domain for my AWS Gateway and a default stage so that going to https://sub.domain.com brings up the homepage for the Spheres app. When I try to go to the admin section the app redirects to https://dev/admin/login/?next=/dev/admin/

I have the domain setting setup in the  zappa settings:
'domain': 'sub.domain.com',

How do I get the django app to use my custom domain that I've setup and get rid of the /dev/ section of the url?

**Comment by Miserlou** [comment]
Good catch, the code for domain support was only being called on 'deploy', not 'update'.

**Comment by Miserlou** [comment]
Fixed in 0.11.2

**Comment by eekolife** [comment]
I ran
==========
$ pip install -U django_zappa
Collecting django-zappa
  Downloading django_zappa-0.11.2-py2-none-any.whl
Requirement already up-to-date: requests>=2.9.1 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: mysql-connector-python-rf==2.1.3 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: wheel==0.24.0 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: zappa==0.11.1 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: Django>=1.8 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: coverage==4.0.3 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: base58==0.2.2 in ./env/lib/python2.7/site-packages (from django-zappa)
Requirement already up-to-date: python-dateutil==2.4.2 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: nose==1.3.7 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: filechunkio==1.6 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: jmespath==0.9.0 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: tqdm==3.7.1 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: botocore==1.3.26 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: wsgi-request-logger==0.4.4 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: docutils==0.12 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: futures==3.0.4 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: six==1.10.0 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: boto==2.39.0 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Requirement already up-to-date: boto3==1.2.3 in ./env/lib/python2.7/site-packages (from zappa==0.11.1->django-zappa)
Installing collected packages: django-zappa
  Found existing installation: django-zappa 0.11.1
    Uninstalling django-zappa-0.11.1:
      Successfully uninstalled django-zappa-0.11.1
Successfully installed django-zappa-0.11.2
============

and then I ran $ python manage.py update dev

I'm still seeing the same behavior.

**Comment by bjinwright** [comment]
I'm still seeing this as well.

**Comment by balu42** [comment]
Same for me. If I remote zappa and zappa middleware from settings admin is working fine, if I leave them in admin redirects back to login after clicking on something on the admin page (after successful login)

**Comment by riceluxs1t** [comment]
+1. I am still seeting

**Comment by codalprashant** [comment]
We are still facing issue. Anyone has any solution ?
