### ISSUE TITLE
Allow Specifying remote settings file using package notation

### ISSUE THREAD

**Issue by cancan101** [Miserlou/django-zappa#29]
ie `myapp.settings.remote.production` and then `inspect.getsource`

**Comment by collingreen** [comment]
Is this in the ZAPPA_CONFIG dict, as a replacement for path notation? Is there a reason driving this or just your preference?

**Comment by cancan101** [comment]
Yes. it adds portability. Right now If I checkout my code into a different location, I need to then go update the paths.

**Comment by collingreen** [comment]
Wouldn't changing to relative paths instead of absolute paths also solve this?

**Comment by cancan101** [comment]
It would certainly be an improvement. Though then you still are relative to ... what? Also this seems pretty non standard for Django conf?

**Comment by collingreen** [comment]
I agree on both the standard-like use and relative paths. I imaging it would be relative to the django root, just like dot notation would be.

**Comment by mathom** [comment]
@cancan101 I'm currently using this in my projects:
```
'settings_file': os.path.join(BASE_DIR, 'MyApp', 'settings.py'),
```

I'm not an expert on django but my auto-generated settings files always define `BASE_DIR` out of the box.
