### ISSUE TITLE
delete / undeploy command

### ISSUE THREAD

**Issue by cancan101** [Miserlou/django-zappa#32]
Create a command that can be run that will clean up the AWS account after the deploy command (ie restore it to how it was). 

Since the IAM role is global, we probably don't want to delete that (by default).

**Comment by Miserlou** [comment]
'undeploy' to remove the function and API gateway seems good, should probably have a confirm though.

**Comment by mathom** [comment]
:+1: I agree. I have some code to do this but I haven't pushed it to a PR yet.

**Comment by collingreen** [comment]
Undeploy is upstream in zappa, so its either coming soon or already landed.

**Comment by cancan101** [comment]
did this ever land?

**Comment by Miserlou** [comment]
Please look here: https://github.com/Miserlou/Zappa/
