### ISSUE TITLE
No integration defined

### ISSUE THREAD

**Issue by eekolife** [Miserlou/django-zappa#4]
When I try to deploy I get this error after the zip file is uploaded and after Creating API Gateway routes.. is printed to the console:

botocore.exceptions.ClientError: An error occurred (NotFoundException) when calling the PutIntegrationResponse operation: No integration defined for method

Any ideas what I might be doing wrong?

**Comment by Miserlou** [comment]
Hmm.. what region are you trying to use? us-east-1?

If that's not it, I'll investigate further when I wake up going to sleep now..

**Comment by eekolife** [comment]
Yes. I set my ~/.aws/config to us-east-1 and left the default in django-zappa

**Comment by Miserlou** [comment]
I really wish I could help more with this but I don't have enough information to help.

Can you help me by providing a complete traceback and a copy of your ZAPPA_SETTINGS?

Does it happen every time, or only occasionally?

**Comment by chris-sf** [comment]
This has happened every time I've tried to get this running. Here's the output from the command:

$ python manage.py deploy dev
Creating ZappaLambdaExecution IAM..
Packaging project as zip..
Uploading zip (28.7MiB)..
Creating API Gateway routes..                                                                                                                                                                                                                                         
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "workspaces/Spheres/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/django_zappa/management/commands/deploy.py", line 117, in handle
    api_id = zappa.create_api_gateway_routes(lambda_arn, lambda_name)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/zappa/zappa.py", line 476, in create_api_gateway_routes
    self.create_and_setup_methods(api_id, resource_id, lambda_arn)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/zappa/zappa.py", line 582, in create_and_setup_methods
    responseTemplates=response_templates
  File "workspaces/Spheres/env/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "workspaces/Spheres/env/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NotFoundException) when calling the PutIntegrationResponse operation: No integration defined for method

Zappa Settings looks like this:

ZAPPA_SETTINGS = {
    'dev' : {
       's3_bucket': 'zappabucketlam',
       'settings_file': './spheres/dev_settings.py'
    }
}

**Comment by Miserlou** [comment]
Thanks! This gives me enough to work with. Will report back soon.

**Comment by Miserlou** [comment]
Hm. Unfortunately, I was unable to reproduce this on a fresh AWS account - it worked. This makes it hard to debug.

Can you give me some more information? Maybe your operating system and python version?

**Comment by Miserlou** [comment]
Looks like you're on a Unixy, P2.7, so that's not it.

So, can you show me:
    - Did the ZappaLambdaExecution role get created (should be there as a Role in the IAM console)
    - Did the zip file get uploaded successfully (should be in S3 console)
    - Were any API Gateway APIs/Routes created (should be in API GW console)

Thanks!

**Comment by Miserlou** [comment]
Are you the administrator of the AWS account? Do you have permissions to create IAM roles?

My suspicion is that you were not able to successfully create the ZappaLambdaExecution, but this failure was not noticed, and an error was caused later in the process.

**Comment by eekolife** [comment]
I'm using OS X 10.11.3 and tried to follow along what you did in the Spheres video. I tried using the built in python (2.7.9) and python (2.7.11) from homebrew. I am the admin in the AWS console. I created an IAM user for myself and attached an AdministratorAccess policy to it. I tried on my personal AWS account and my work account.

The ZappaLambaExecution role is created with zappa-permissions inline policy.
There's an api gateway created called Spheres-dev (3 resources, 2 models, 0 stages)
There's a lambda function created called Spheres-dev.

**Comment by Miserlou** [comment]
Interesting!

By default, I think there should be 5 resources, 2 models, and 1 stage. I wonder why it messed up on the 4th.. are you on a really good internet connection? Maybe it's hitting Amazon too fast?

If you click on the API in the API GW console, there should be a big blue Deploy API button. Are you able to successfully deploy the application manually?

Should look like this..
<img width="994" alt="screen shot 2016-02-12 at 2 17 16 pm" src="https://cloud.githubusercontent.com/assets/139987/13007887/5ef8d572-d193-11e5-910f-8ae2f17417cb.png">

**Comment by eekolife** [comment]
Trying to deploy using the Deploy API button give me the same error
![screen shot 2016-02-12 at 9 14 39 am](https://cloud.githubusercontent.com/assets/847769/13009215/219b6232-d169-11e5-8bde-d2a01e71d2ee.png)

And my Resources is missing some information. It does not look like yours:
![screen shot 2016-02-12 at 9 15 50 am](https://cloud.githubusercontent.com/assets/847769/13009228/3c2a572a-d169-11e5-98f2-f85a1563faa9.png)

I do have a fast connection, but I'm not sure that's it.

**Comment by eekolife** [comment]
Trying it a few more times gives me this. I'm not sure I did anything different:
![screen shot 2016-02-12 at 9 29 08 am](https://cloud.githubusercontent.com/assets/847769/13009576/26676e30-d16b-11e5-82e8-04b4b342e395.png)

Still ends in the same error and doesn't match what you have.

**Comment by Miserlou** [comment]
The fact that this is so inconsistent and difficult to reproduce makes me
think that this is connection based. I only ever tested this on crappy
hotel wifi, not a proper connection, but I know that Amazon doesn't like it
when you hammer it too much.

Are you comfortable editing the zappa code to add a small delay in the
loop? If not, I could add this in a version bump and have it be a
configurable setting?

**Comment by eekolife** [comment]
That seems to have worked. I added:
`time.sleep(1) # delay for 1 second`
to line 477 of zappa.py and it worked on the first try.

Thanks for your help.

**Comment by Miserlou** [comment]
Ah, gotcha.

Okay, I'll add that in and make it configurable.

Thanks for reporting this, and thanks for your patience!

Let me know if there's anything else I can do to improve Zappa.
