### ISSUE TITLE
Minor optimizations to handler.py

### ISSUE THREAD

**Issue by cristianocca** [Miserlou/django-zappa#45]
I'm sorry I'm extremely lazy to create a pull request, but looking at handler.py while trying to help out with an issue at the django forums I noticed some really minor optimizations that you can do (they are really minor and won't change any timing significantly, but it is always good to do things in the best way as possible, every milisecond counts!)

Debug and logger calls: Are you using AWS logging? If I'm not wrong that goes to cloud watch which can be pretty slow, I would really avoid any logging when debug is false and do not test any timings with code that writes to those logs.

Line 61, def start(a,b)... Defining a function over and over is quite expensive, and nested functions are a bit more expensive on python also. I would have that one defined at module level only once.

Line 87: if response.status_code in [400, 401, 403, 404, 500]: You are defining this list over and over, and also the IN operator on a list is always O(n) worst case, I would define this list as a global variable and even better make it a set or dictionary which will be O(1) most of the time (although for such a small list, the difference is really small, on a 10000000 loop it is about 25% faster on python2.7)

Overall, try to use either format or % operator for string concatenation, it is way more efficient and readable than +

I couldn't find how does the common_log work, but you are calling it every time even with no debug, which might be giving you some unnecessary slowdowns.

**Comment by mathom** [comment]
I believe concatenation is usually faster than a string format, at least for small strings: http://stackoverflow.com/a/33981580

**Comment by mathom** [comment]
As with any optimization, benchmarking it before and after is always a good idea in case it doesn't turn out the way you expect :grinning:

**Comment by Miserlou** [comment]
common_log writing to CloudTrail, as you suggested. It puts them into the common access.log format. If there were a way to delay this, I'd be into that.

**Comment by cristianocca** [comment]
@mathom You are right about string concatenation, for the list defined locally vs set globally I have tested it with this, commenting both "d"s defined.

import time
values = [200, 201, 301, 302, 400, 401, 403, 404, 500]
d = {400, 401, 403, 404, 500}

timer = time.clock()

a = 0
for i in xrange(10000000):
	#d = [400, 401, 403, 404, 500]
	if values[i % 9] in d:
		a+=1
		
print time.clock() - timer

Similar test to def start(a,b)

@Miserlou would it be enough with logging only with debug on? How much time is used on that log? I don't know how fast that is but probably involves a network request which will add overhead. I don't think there's any easy way to pospone that as the lambda call will be either dead or frozen after the request is done. The only idea I can think of is to use a thread pool (even if it is only 1 thread) initialized at module level and sending the log call to the pool, but I don't think you have guarantees that will correctly finish nor improve the call at all.

**Comment by mathom** [comment]
[Timeit](https://docs.python.org/2/library/timeit.html) is pretty handy for testing stuff like this, too

**Comment by Miserlou** [comment]
I haven't looked into threading on Lambda yet.. sounds a bit insane.. and I'm not even sure that the over-head of setting up the threads would be less than the cost of the log request! :)

I personally think logging is an application must, although this should be made configurable in the Zappa-Settings.

I was using the 'pprofile' library to profile this stuff before, you can see the output of that in the other ticket.

**Comment by cristianocca** [comment]
@mathom Thank you, I know it but never actuall used it

@Miserlou Thanks for the other ticket, if I read it right the time taken with common_log is ~2.5ms ? Seems quite low.

The reason I stated about this is because Rich Jone's thread on the django forums about django.setup() taking too long, which resulted in that not being an issue really since AWS would re use the enviorment for multiple requests.
Is there a way you can generate the same file but with the change he did to move django.setup() to module level? Ideally the result file should be the one from a reused enviorment so you don't count the setup call and there are less lines to read

**Comment by adamchainz** [comment]
> Debug and logger calls: Are you using AWS logging? If I'm not wrong that goes to cloud watch which can be pretty slow, I would really avoid any logging when debug is false and do not test any timings with code that writes to those logs.

I think Lambda bunches up logs locally on the machines the functions run on and then pushes them to CWL in the background. In my experience (with non-zappa lambdas) the logging seems to be delayed a bit.

**Comment by Miserlou** [comment]
That's very certainly a possibility. If you use the 'python manage.py tail' command, you can see that there is a slight delay in the logs.

**Comment by adamchainz** [comment]
Ah neat, check out https://github.com/jorgebastida/awslogs for CWL too
