### ISSUE TITLE
Avoid creating zip files with weird filenames

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/django-zappa#46]
Just created an annoying zip called '..-demo-1457630734.zip'. Let's avoid doing that.

**Comment by Miserlou** [comment]
Worse still: botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value '..-demo' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?

**Comment by Miserlou** [comment]
It's in DZ, the result of this:

        self.project_name = settings.BASE_DIR.split(os.sep)[-1]
        self.lambda_name = self.project_name + '-' + self.api_stage

BASE_DIR isn't even guaranteed, or it can contain weird stuff like '..' in it - is there a better way of getting the Django project name?

**Comment by Miserlou** [comment]
Ah, that works! Ok.

Does Django>=1.8 require BASE_DIR? If so, I can close, but it still feels slightly sloppy.

**Comment by Doerge** [comment]
Just searched for it. https://github.com/django/django/blob/master/django/conf/project_template/project_name/settings.py-tpl this template uses `abspath` as well, so I guess that is the _correct_ to go about this. But again I know nothing about Django... yet :)

**Comment by Miserlou** [comment]
Good enough for me!

**Comment by Doerge** [comment]
Also `__file__` in python +3.4/5'ish will return absolute paths in _most_ (perhaps all?) cases as I understand it from this: http://bugs.python.org/issue18416
