### ISSUE TITLE
Feature request consideration: Azure Functions

### ISSUE THREAD

**Issue by jamespacileo** [Miserlou/django-zappa#51]
Hi chaps,

apologies for raising this if it's out of scope.

I've read news about Azure Functions being introduced, and apparently there is less of a cold start issue and Functions are guaranteed to stay hot for at least 5 minutes.

Here is a link to Azure Functions:
https://azure.microsoft.com/en-us/services/functions/

**Comment by Miserlou** [comment]
Yeah, it's interesting. Having different backends would be great (Google Cloud Functions are another interesting target) but the big issue here is really that most of the work of Zappa has been done at the API Gateway level, not at the Lambda level, and so far I don't think I've seen any cloud function service that has an equivalent API Gateway.

If either Google or Microsoft is willing to fund development of Zappa/GCF/AF, that's a different story.

**Comment by collingreen** [comment]
Willing to fund AND support -- as @Miserlou mentioned, without a solid enough http interface to the cloud function host the entire idea is dead in the water. API Gateway is just enough to work although it could use some serious love as well.
