### ISSUE TITLE
Feature Request: Allow loading settings file from S3

### ISSUE THREAD

**Issue by bjinwright** [Miserlou/django-zappa#54]
For developers that work on a team where everyone doesn't have production deployment privileges, loading the settings file from S3 would be helpful. If the user's IAM credentials don't give them access to the S3 file they can't access the settings file. We can already limit the ability to create or update Lambda function code and API Gateway resources via IAM policies.

ZAPPA_SETTINGS = {
    'production': {
       's3_bucket': 'production-bucket',
       'settings_file': 's3://your_bucket:your_folder/production_settings.py',
    },
    'staging': {
       's3_bucket': 'staging-bucket',
       'settings_file': '~/Projects/MyApp/settings/staging_settings.py',
    },
}

**Comment by bjinwright** [comment]
Couple that with the upcoming  redeploy command this is a devops dream.

**Comment by bjinwright** [comment]
I can work on this if you all like the idea and think you'd be willing to pull it in.

**Comment by Miserlou** [comment]
It's funny you brought this up, it has been specifically suggested on Slack before for this exact reason. I think it's a great idea.
