### ISSUE TITLE
[Questions] Error "Unable to import module 'handler'" and other doubts

### ISSUE THREAD

**Issue by ShipraShalini** [Miserlou/django-zappa#59]
I created a project for building leaderboards using redis and it was causing import errors with djang-zappa..

So I have created a [django project](https://github.com/ShipraShalini/sample) for trying out django-zappa.
It works fine on my local system but when I hit the api provided by django-zappa, I get following error: 

> Unable to import module 'handler': No module named django.core.handlers.wsgi

Also the endpoints created by django-zappa in API Gateway look like 
<img width="180" alt="screen shot 2016-04-22 at 12 38 10 pm" src="https://cloud.githubusercontent.com/assets/9088430/14734317/4228ecfe-0887-11e6-8c52-291498cfbc94.png">

Am I supposed to pass some parameters to django-zappa? If yes, how?

Do I need to explicitly create API endpoints in Lambda as I didn't see any in the Lambda console??

**Comment by Miserlou** [comment]
Are you using your project from inside a virtualenvironment? How large is your package? What is your endpoint URL?

You shouldn't need to do anything special to use d-z.

**Comment by ShipraShalini** [comment]
Hi Miserlou,
I'm using my project from inside a virtualenv. 
The project sends a response "hello" on hitting the endpoint /hello.

On zipping the project I get a total of 267 MB (Is this what you were asking?) while my django project is max 5 statements.

**Comment by jwojcik** [comment]
It seems as though none of the libraries are making it into the lambda function package zip file. All I see is MySQLdb and none other.
