### ISSUE TITLE
Django-Zappa is Not Python3 Ready Yet

### ISSUE THREAD

**Issue by tcross911** [Miserlou/django-zappa#60]
Hello,

I have tried multiple times to run the deploy from various environments, and each time I run into this set of errors: https://gist.github.com/anonymous/0b078b15465bb3ab104e3ed9f631acfb

I am running Django 1.9.5 with Python 3.4.4

**Comment by Miserlou** [comment]
This is because Zappa isn't fully Python 3 compatible yet. :(

My fault. I'm still on P2.7. I normally try to write 2/3 compatible code, but I forgot about has_key.. Gahhh..

**Comment by tcross911** [comment]
Ok, that makes sense.  Since it was listed on Pypi supporting some versions of python 3 (3.3 on), I thought it was :)

**Comment by Miserlou** [comment]
!!! Good catch. I think it was at some point, but apparently not any more.

The complicating part is that AWS Lambda only support Python 2.7 for now, and I don't know what that'll do for the deployments if the virtualenvironments have P3 versions of packages.

**Comment by zkanda** [comment]
Its quite a bit involved: http://www.cloudtrek.com.au/blog/running-python-3-on-aws-lambda/
@Miserlou Are you okay with this kind of hackery? I might try to send a PR if this is okay.

**Comment by toc14C** [comment]
Too bad! Looking forward to 3.5 functional just let me know if there is anyway I can help!
