### ISSUE TITLE
SSL Handshake Error when deplying API Gateway

### ISSUE THREAD

**Issue by tcross911** [Miserlou/django-zappa#61]
Hello,

Sorry to come with another issue, luckily I am just working on a small test project so switching from python 3.4 to python 2.7.6 was easy enough since I am not doing much that is impacted by switching versions (just testing mostly) though now when I run the deploy, it bundles the files up nicely, creates the lambda app, then create the API Gateway part which seems to complete without issue, but now when Deploying the API Gateway it errors with this: https://gist.github.com/tcross911/369d204d983919a1bbb236831206ef56

**Comment by Miserlou** [comment]
This actually bit somebody else the other day, https://github.com/Miserlou/Zappa/issues/69

Can you try:

    pip install requests[security]

?

**Comment by tcross911** [comment]
That definitely fixed the issue, had a few other issues after that, but those were issues with my code (forgot urllib.parse doesn't exist in 2.7 and it is urlparse for example).  Thanks so much for the help.

**Comment by Miserlou** [comment]
Great! Thanks for reporting, and thanks for using Zappa!
