### ISSUE TITLE
Allow defining requirements.txt files per-environment (Was: Arbitrary path and includable requirements.txt)

### ISSUE THREAD

**Issue by stringfellow** [Miserlou/django-zappa#7]
It looks like the repo needs a singular static `requirements.txt` file - I'm quite used to having at least 3, one for common stuff, one for dev and one for prod (and the latter 2 include the former).

I had a quick skim of the code and it looks like it's looking for the lines of `requirements.txt` in `setup.py` -- looks like there's a package (`requirements-parser`) that can slot in here, making the requirements an arg somewhere:

```
In [1]: import requirements
In [2]: fp = open('requirements/dev.txt')
In [3]: list(requirements.parse(fp))
Out[3]:
[<Requirement: "Pillow==2.8.1">,
 <Requirement: "boto==2.38.0">,
 <Requirement: "hashids==1.1.0">,`
...
```

**Comment by Miserlou** [comment]
Kind of confused by this comment - why would we need dev and prod requirements for a library?

**Comment by collingreen** [comment]
I think the requirements file(s) mentioned are for the django project being deployed, not for the django-zappa library itself.

**Comment by Miserlou** [comment]
I'm not sure what I'm supposed to do here.

To clarify - Zappa deploys off of the _contents_ of the virtual environment, not a requirements file. If you want to deploy different environments to different stages, you will need multiple venvs.

**Comment by collingreen** [comment]
That's a really good point. I suppose multiple venvs is a fine solution, although I've never done such a thing before and I also usually have different requirements.txt files per environment.

**Comment by Miserlou** [comment]
The only similar alternative I could think of is having a setting in the ZAPPA_SETTINGS for something like

    virtualenv_path 

Which would use that as the working venv, or, alternately,

    requirements_path

That would create a NEW venv, install all the requirements, THEN create and upload the Zappa package. This may considerably slow down deploy and update. But I'm open to the idea.

**Comment by collingreen** [comment]
Maybe the new virtualenv could be created in a hidden file (.zappa_venv?) and include the requirements.txt (or just a hash) that was used to create it. Then the build process can just compare the requirements.txt against the venv and only rebuild it if necessary. The first deploy would be longer, but everything else would still be fast (as long as the requirements aren't changing, which is rare).

**Comment by Miserlou** [comment]
Ah, good idea, that's what I was thinking for the first bit, but we can
actually do one better by combing them and calling the venvs something like

.zappa_781e9d37c240292f4ec8af399bdac5d2c2e3e621

**Comment by collingreen** [comment]
As long as it cleans up out of date venvs intelligently, that sounds awesome.

**Comment by Miserlou** [comment]
What do you mean? I'm wearing of things that try to "intelligently" delete
things. I think this is something people might just have to be mindful
about themselves, although I doubt it'll every be a big problem.

**Comment by collingreen** [comment]
My only concern is ending up with 100 venvs and only 2 of them are used, although it is unreasonable to change the requirements that much so maybe the point is irrelevant.

**Comment by stringfellow** [comment]
Wow - that escalated quickly! ;) Yeah sorry for the confusion - I misunderstood how it gets a venv set up on lambda but I'm new to lambda and was trying to figure through the code! I watched the screencast but it wasn't totally clear how the environment ends up where it executes remotely. But anyway, where you've got to in this discussion sounds pretty useful - low-effort deployments are a dream :)

**Comment by collingreen** [comment]
Escalated? Hopefully not in a bad way!

**Comment by stringfellow** [comment]
Haha, no all good :) Just playing

**Comment by Miserlou** [comment]
@collingreen - do you want to try implementing this?

**Comment by collingreen** [comment]
I don't mind but I have a couple other things I've started on that I think are higher priority -- some readme updates with missing steps and troubleshooting, some stuff I wanted to talk to you about boto (I had to make a bunch of changes to how zappa creates boto clients to make it work at all, but you clearly did not, so I just need more info at this point), and some build test coverage to suss out some issues with using regions that aren't us-east-1.

**Comment by Miserlou** [comment]
Oh hell yeah! Sounds great to me.

**Comment by collingreen** [comment]
@Miserlou if you've settled on a way forward, maybe rename the issue to reflect the plan, or close it and open a new one?

**Comment by Miserlou** [comment]
Done

**Comment by collingreen** [comment]
:+1:
