### ISSUE TITLE
Ability to specify routes in ZAPPA_SETTINGS

### ISSUE THREAD

**Issue by JamesWilmot** [Miserlou/django-zappa#70]
Would be convenient if had ability to specify which routes API gateway resources/methods were created. 

I've had a look myself and I might tackle it soonish. Hopefully. 

Thanks for all the hard work on this amazing project!

**Comment by Miserlou** [comment]
Thanks @JamesWilmot !

Can you describe a bit more about what you mean by this? Do you mean just for the purpose of reducing API Gateway route creation time? 

If so, I think that I'd greatly prefer to solve that problem using this: https://github.com/Miserlou/Zappa/issues/84
