### ISSUE TITLE
Relative imports do not work in settings file

### ISSUE THREAD

**Issue by eldos-dl** [Miserlou/django-zappa#77]
Any relative imports in settings files do not work as it is being copied to a different location.

**Comment by Miserlou** [comment]
Can you give me an example to help reproduce? Where are your settings file located?

**Comment by eldos-dl** [comment]
```
settings
├── base.py
├── __init__.py
├── production.py
└── staging.py
```

This is the structure of my settings directory in my application. I import settings from **base.py** in **production.py** and **staging.py**
```
from base import *
```

**Comment by Miserlou** [comment]
Gotcha, thanks for reporting. Will try to get to this when I can, but will accept PR!

**Comment by zkanda** [comment]
If anyone is looking for a workaround, do a full path import.

e.g. `from <project_name>.settings.base import *`

@Miserlou can you give some points on how to fix this?
