### ISSUE TITLE
How to remove the environment prefix in the URL.

### ISSUE THREAD

**Issue by zkanda** [Miserlou/django-zappa#80]
So I deployed my app in Lambda, with the URL like this `https://16xf96vt2l.execute-api.eu-central-1.amazonaws.com/production/`.

How do I remove `/production/` on it?

**Comment by aaronleese** [comment]
yeah, good question .. I've been wanting to do this too ...

**Comment by collingreen** [comment]
As far as I know, this isn't a thing you can do with api gateway unless you add your own domain.

**Comment by zkanda** [comment]
Yes indeed, which sad, closing this.
