### ISSUE TITLE
S3 upload unusual issue

### ISSUE THREAD

**Issue by aaronleese** [Miserlou/django-zappa#87]
Hey all - 

First off, great job on all of this! I've been loving Zappa, and can't wait to migrate all of my applications over to using it.

But - I currently have an issue that I would love some clarity on.

I've integrated Boto and S3 static and media hosting, as described here:
https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/

It works quite well, but there is some weirdness when deployed with Zappa.

Specifically, when running locally, all files are uploaded as expected to the S3 servers (I'm just testing through the /admin console).

When running on a Zappa deploy, some uploaded files are mangled (they end up being twice as large as they should be). Generally, I am trying to upload audio files ... and the result is an invalid file.
Text files work fine though ... which leads me to believe it has something to do with escape characters getting added? Since the audio files are non-ASCII in nature.

So ... to sum it up:

Running at **localHost:8000, and using /admin** ... I can upload FileFields to S3:
- **_Text files work fine_**
- **_Audio files work fine_**

Running **remotely as a Zappa deploy, and using /admin** ... I can upload FileFields to S3:
- **_Text files work fine_**
- **_Audio files get horribly destroyed, coming out at about twice the normal file-size_**

Also, running the same code on an EC2 instance works just fine ... so it must be something with the fact that it is running serverless?

Not sure ... but hoping someone here might have an idea :)

**Comment by anush0247** [comment]
@aaronleese please refer https://github.com/Miserlou/Zappa/issues/80
