### ISSUE TITLE
Move Django Middleware to WSGI Middleware

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/django-zappa#9]
It was pointed out during the Q & A that the Django Middleware could be replaced with a WSGI Middleware that would live in Zappa core. This has a number of obvious benefits, such as more shared code, less client-specific code, and less client-specific integration.

**Comment by codingjoe** [comment]
:+1: eventually this will also allow you to hook any WSGI application on ![lambda](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Greek_lc_lamda_thin.svg/100px-Greek_lc_lamda_thin.svg.png)

**Comment by Miserlou** [comment]
Looking forward to your PR @codingjoe ! :stuck_out_tongue_winking_eye:

**Comment by Doerge** [comment]
I have written an initial WSGI middleware for flask-zappa.

It's not quite there yet, but I'm still working on it. If anyone want to give it a spin with Django it can [be found here.](https://github.com/Doerge/Zappa/blob/master/zappa/middleware.py).

**Comment by Miserlou** [comment]
Excellent work! Werkezeug was a good choice, and I'm happy to see the middleware moving upstream.
